/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.characterpaint {
	import laya.ui.*;
	import laya.display.*;

	public class CharacterPaintUI extends View {
		public var panel_main:Panel;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("characterpaint/CharacterPaint");

		}

	}
}