/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.characterpaint {
	import laya.ui.*;
	import laya.display.*;
	import script.characterpaint.CharacterTypeChooseControl;

	public class CharactTypePanelUI extends Scene {
		public var panel_main:Panel;
		public var qiegebtn:Button;
		public var glowbtn:Button;
		public var ironbtn:Button;
		public var closebtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("characterpaint/CharactTypePanel");

		}

	}
}