/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.characterpaint {
	import laya.ui.*;
	import laya.display.*;

	public class ColorLblItemUI extends View {
		public var lblcolor:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":0,"height":0},"compId":2,"child":[{"type":"Label","props":{"width":90,"var":"lblcolor","height":30,"borderColor":"#101010","bgColor":"#f41815"},"compId":3}],"loadList":[],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}