/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.common {
	import laya.ui.*;
	import laya.display.*;
	import utils.PicturePopUpController;

	public class PicturePopDialogUI extends View {
		public var mainpanel:Panel;
		public var mainview:Image;
		public var msgtxt:Label;
		public var okbtn:Button;
		public var cancelbtn:Button;
		public var closebtn:Button;
		public var tipimg:Image;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("common/PicturePopDialog");

		}

	}
}