/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package {
	import laya.utils.ClassUtils;
	import laya.ui.View;
	import laya.webgl.WebGL;
	import script.login.LogPanelControl;
	import laya.display.Text;
	import script.login.RegisterCntrol;
	import script.login.ResetPwdControl;
	import script.MainPageControl;
	import script.order.SelectAddressControl;
	import script.order.SelectFactoryControl;
	import laya.html.dom.HTMLDivElement;
	import script.order.SelectPicControl;
	import script.order.PaintOrderControl;
	import script.picUpload.PicManagerControl;
	import script.picUpload.PictureCheckControl;
	import utils.PopUpWindowControl;
	import script.picUpload.UpLoadAndOrderContrl;
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var width:int = 640;
		public static var height:int = 1136;
		public static var scaleMode:String = "fixedwidth";
		public static var screenMode:String = "none";
		public static var alignV:String = "top";
		public static var alignH:String = "left";
		public static var startScene:* = "order/SelectPicPanel.scene";
		public static var sceneRoot:String = "";
		public static var debug:Boolean = false;
		public static var stat:Boolean = false;
		public static var physicsDebug:Boolean = false;
		public static var exportSceneToJson:Boolean = true;
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
			reg("script.login.LogPanelControl",LogPanelControl);
			reg("laya.display.Text",Text);
			reg("script.login.RegisterCntrol",RegisterCntrol);
			reg("script.login.ResetPwdControl",ResetPwdControl);
			reg("script.MainPageControl",MainPageControl);
			reg("script.order.SelectAddressControl",SelectAddressControl);
			reg("script.order.SelectFactoryControl",SelectFactoryControl);
			reg("laya.html.dom.HTMLDivElement",HTMLDivElement);
			reg("script.order.SelectPicControl",SelectPicControl);
			reg("script.order.PaintOrderControl",PaintOrderControl);
			reg("script.picUpload.PicManagerControl",PicManagerControl);
			reg("script.picUpload.PictureCheckControl",PictureCheckControl);
			reg("utils.PopUpWindowControl",PopUpWindowControl);
			reg("script.picUpload.UpLoadAndOrderContrl",UpLoadAndOrderContrl);
		}
		GameConfig.init();
	}
}