/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.product {
	import laya.ui.*;
	import laya.display.*;

	public class AdvertiseItemUI extends View {
		public var proName:Label;
		public var proPrice:Label;
		public var proNum:TextInput;
		public var btnadd:Button;
		public var btnsub:Button;
		public var btnok:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":480,"height":0},"compId":2,"child":[{"type":"Image","props":{"skin":"commers/inputfocus.png","sizeGrid":"5,5,5,5","right":0,"left":0,"height":30},"compId":11},{"type":"Label","props":{"y":6,"x":5,"width":186,"var":"proName","text":"户内无纸背胶","height":16,"fontSize":16,"font":"SimHei"},"compId":3},{"type":"Label","props":{"y":8,"x":209,"width":76,"var":"proPrice","text":"￥23.6元","height":16,"fontSize":16,"font":"SimHei","color":"#dd3432"},"compId":4},{"type":"Sprite","props":{"y":3,"x":295},"compId":5,"child":[{"type":"TextInput","props":{"y":1,"x":19,"width":40,"var":"proNum","text":"10","skin":"commers/inputbg.png","sizeGrid":"3,3,3,3","height":22,"fontSize":16,"font":"SimHei","color":"#262B2E","align":"center"},"compId":6},{"type":"Button","props":{"x":60,"var":"btnadd","skin":"order1/addbtn.png"},"compId":7},{"type":"Button","props":{"var":"btnsub","skin":"order1/subtbn.png"},"compId":8}]},{"type":"Button","props":{"y":2,"x":381,"width":91,"var":"btnok","skin":"commers/btn1.png","sizeGrid":"2,2,2,2","labelSize":16,"labelFont":"SimHei","labelColors":"#FFFFFF,#FFFFFF,#FFFFFF","label":"移出购物车","height":25},"compId":10}],"loadList":["commers/inputfocus.png","commers/inputbg.png","order1/addbtn.png","order1/subtbn.png","commers/btn1.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}