/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.product {
	import laya.ui.*;
	import laya.display.*;

	public class AdvertiseItemUI extends View {
		public var proName:Label;
		public var proPrice:Label;
		public var proNum:TextInput;
		public var btnadd:Button;
		public var btnsub:Button;
		public var btnok:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":415,"height":0},"compId":2,"child":[{"type":"Label","props":{"y":5,"x":0,"width":118,"var":"proName","text":"商品名称六个字","height":16,"fontSize":16,"font":"SimHei"},"compId":3},{"type":"Label","props":{"y":5,"x":129,"width":76,"var":"proPrice","text":"￥23.6元","height":16,"fontSize":16,"font":"SimHei","color":"#dd3432"},"compId":4},{"type":"Sprite","props":{"y":0,"x":222},"compId":5,"child":[{"type":"TextInput","props":{"y":1,"x":19,"width":40,"var":"proNum","text":"10","skin":"commers/inputbg.png","sizeGrid":"3,3,3,3","height":22,"fontSize":16,"font":"SimHei","color":"#262B2E","align":"center"},"compId":6},{"type":"Button","props":{"x":60,"var":"btnadd","skin":"order/addbtn.png"},"compId":7},{"type":"Button","props":{"var":"btnsub","skin":"order/subtbn.png"},"compId":8}]},{"type":"Button","props":{"y":2,"x":316,"width":91,"var":"btnok","skin":"commers/btn1.png","sizeGrid":"2,2,2,2","labelSize":16,"labelFont":"SimHei","labelColors":"#FFFFFF,#FFFFFF,#FFFFFF","label":"加入购物车","height":25},"compId":10}],"loadList":["commers/inputbg.png","order/addbtn.png","order/subtbn.png","commers/btn1.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}