/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.product {
	import laya.ui.*;
	import laya.display.*;
	import script.product.BuyProductControl;

	public class BuyProductPanelUI extends View {
		public var productimg:Image;
		public var proname:Label;
		public var size0:Button;
		public var size1:Button;
		public var pricetxt:Label;
		public var numinput:TextInput;
		public var btnbuy:Button;
		public var btnclose:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("product/BuyProductPanel");

		}

	}
}