/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.product {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.prefabScript.TopBannerControl;
	import script.product.ProductMainControl;

	public class ProductOrderPanelUI extends View {
		public var mainpanel:Panel;
		public var firstPage:Text;
		public var myorder:Text;
		public var userName:Text;
		public var logout:Text;
		public var productlist:List;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("product/ProductOrderPanel");

		}

	}
}