/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.product {
	import laya.ui.*;
	import laya.display.*;

	public class ProductCateItemUI extends View {
		public var catebtn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":0,"height":0},"compId":2,"child":[{"type":"Button","props":{"y":0,"x":0,"width":194,"var":"catebtn","stateNum":3,"skin":"order1/selection.png","sizeGrid":"3,3,3,3","labelSize":16,"labelFont":"SimHei","labelColors":"#262B2E,#463B4E,#262B2E","label":"户内PP背胶（户内写真）","height":42},"compId":3}],"loadList":["order1/selection.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}