/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.product {
	import laya.ui.*;
	import laya.display.*;

	public class TreeClipUI extends View {

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":0,"height":0},"compId":2,"child":[{"type":"Clip","props":{"y":0,"x":13,"skin":"comp/clip_selectBox.png","name":"selectBox","clipY":2,"clipX":1},"compId":3},{"type":"Clip","props":{"y":4,"x":14,"skin":"comp/clip_tree_folder.png","name":"folder","clipY":3,"clipX":1},"compId":4},{"type":"Clip","props":{"y":5,"x":0,"skin":"comp/clip_tree_arrow.png","name":"arrow","clipY":2,"clipX":1},"compId":5},{"type":"Label","props":{"y":1,"x":33,"width":76,"valign":"middle","text":"商品名称","name":"label","height":16},"compId":6}],"loadList":["comp/clip_selectBox.png","comp/clip_tree_folder.png","comp/clip_tree_arrow.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}