/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;
	import script.activity.ActivityAdvertiseController;

	public class ChargeAdvertisePanelUI extends View {
		public var mainview:Image;
		public var closebtn:Button;
		public var ruletxt:Label;
		public var gotocharge:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("ChargeAdvertisePanel");

		}

	}
}