/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;
	import script.MainPageControl;

	public class LoginViewUI extends Scene {
		public var panel_main:Panel;
		public var txt_login:Label;
		public var txt_reg:Label;
		public var btnUserCenter:Button;
		public var btnBuyCar:Button;
		public var btnUpload:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("LoginView");

		}

	}
}