/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.prefabScript.TopBannerControl;
	import script.order.PaintOrderControl;

	public class PaintOrderPanelUI extends View {
		public var firstPage:Text;
		public var myorder:Text;
		public var userName:Text;
		public var logout:Text;
		public var textDeliveryType:Label;
		public var textProductNum:Label;
		public var textTotalPrice:Label;
		public var textDiscountPrice:Label;
		public var textPayPrice:Label;
		public var myaddresstxt:Text;
		public var qqContact:Button;
		public var factorytxt:Text;
		public var selectAll:CheckBox;
		public var btnaddpic:Button;
		public var batchChange:Button;
		public var panel_main:Panel;
		public var mainvbox:VBox;
		public var ordervbox:VBox;
		public var deliverybtn:Text;
		public var deliverytxt:Label;
		public var commentall:TextInput;
		public var btnordernow:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("PaintOrderPanel");

		}

	}
}