/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.login {
	import laya.ui.*;
	import laya.display.*;

	public class CityAreaItemUI extends View {
		public var productname:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":170,"height":26},"compId":2,"child":[{"type":"Label","props":{"width":170,"var":"productname","valign":"middle","top":0,"text":"江西省","left":0,"height":24,"fontSize":24,"color":"#f8f1f1","align":"center"},"compId":3}],"loadList":[],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}