/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.login {
	import laya.ui.*;
	import laya.display.*;
	import utils.LoadingPrgControl;

	public class LoadingPanelUI extends View {
		public var prg:ProgressBar;
		public var prgtxt:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("login/LoadingPanel");

		}

	}
}