/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.login {
	import laya.ui.*;
	import laya.display.*;
	import script.login.LogPanelControl;
	import laya.display.Text;

	public class LogPanelUI extends View {
		public var bgimg:Image;
		public var input_account:TextInput;
		public var input_pwd:TextInput;
		public var btn_login:Button;
		public var closebtn:Button;
		public var txt_reg:Text;
		public var txt_forget:Text;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("login/LogPanel");

		}

	}
}