/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.login {
	import laya.ui.*;
	import laya.display.*;
	import script.login.ResetPwdControl;

	public class ResetPwdPanelUI extends View {
		public var btnClose:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("login/ResetPwdPanel");

		}

	}
}