/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.login {
	import laya.ui.*;
	import laya.display.*;
	import script.login.ResetPwdControl;

	public class ResetPwdPanelUI extends View {
		public var mainpanel:Panel;
		public var inputphone:TextInput;
		public var inputpwd:TextInput;
		public var inputcfmpwd:TextInput;
		public var inputcode:TextInput;
		public var btngetcode:Button;
		public var btnClose:Button;
		public var btnok:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("login/ResetPwdPanel");

		}

	}
}