/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.picManager {
	import laya.ui.*;
	import laya.display.*;

	public class DirectItemUI extends View {
		public var outimg:Image;
		public var foldname:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"width":270,"var":"outimg","skin":"commers/blackbg.png","height":30},"compId":3},{"type":"Label","props":{"y":0,"x":0,"width":270,"var":"foldname","text":"我的图片","height":24,"fontSize":24,"color":"#eaf3ec","alpha":0.8,"align":"center"},"compId":5}],"loadList":["commers/blackbg.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}