/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.picManager {
	import laya.ui.*;
	import laya.display.*;
	import script.picUpload.PictureCheckControl;

	public class PicCheckPanelUI extends View {
		public var img:Image;
		public var closeBtn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":1920,"height":1080},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"top":0,"skin":"commers/blackbg.png","right":0,"left":0,"bottom":0,"alpha":0.8},"compId":3},{"type":"Image","props":{"y":36,"x":560,"width":800,"var":"img","height":800},"compId":4},{"type":"Button","props":{"y":13,"x":1570,"width":75,"var":"closeBtn","skin":"comp/button.png","labelSize":24,"label":"X","height":43},"compId":5},{"type":"Script","props":{"runtime":"script.picUpload.PictureCheckControl"},"compId":6}],"loadList":["commers/blackbg.png","comp/button.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}