/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.picManager {
	import laya.ui.*;
	import laya.display.*;
	import script.picUpload.PictureCheckControl;

	public class PicCheckPanelUI extends View {
		public var mainpanel:Panel;
		public var img:Image;
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("picManager/PicCheckPanel");

		}

	}
}