/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.picManager {
	import laya.ui.*;
	import laya.display.*;

	public class PicShortItemUI extends View {
		public var sel:Image;
		public var img:Image;
		public var fileinfo:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":0,"height":0},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"width":204,"var":"sel","skin":"commers/sel.png","sizeGrid":"10,10,10,10","height":204},"compId":6},{"type":"Image","props":{"y":2,"x":2,"width":200,"var":"img","skin":"comp/image.png","height":200},"compId":3},{"type":"Label","props":{"y":212,"x":0,"wordWrap":true,"width":200,"var":"fileinfo","text":"名称.jpg 宽 3256","height":45,"fontSize":18,"color":"#eee6e6","align":"center"},"compId":4}],"loadList":["commers/sel.png","comp/image.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}