/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.chargeActivity {
	import laya.ui.*;
	import laya.display.*;
	import script.activity.ChargeActRecordController;

	public class ChargeActRecordPanelUI extends View {
		public var recordlist:List;
		public var closebtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("chargeActivity/ChargeActRecordPanel");

		}

	}
}