/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.ChargeControl;

	public class ChargePanelUI extends View {
		public var confirmcharge:Button;
		public var accout:Label;
		public var moneytxt:Label;
		public var actMoney:Label;
		public var frezeMoney:Label;
		public var chargeinput:TextInput;
		public var tyepgrp:RadioGroup;
		public var actpanel:Image;
		public var acttitle:Label;
		public var actrule:Label;
		public var chargeamount:TextInput;
		public var paytype:RadioGroup;
		public var joinact:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/ChargePanel");

		}

	}
}