/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;

	public class ChargePanelUI extends View {

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/ChargePanel");

		}

	}
}