/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;

	public class EnterPrizeInfoPaneUI extends View {

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":800,"height":0},"compId":2,"child":[{"type":"Label","props":{"y":20,"x":35,"text":"账户资料","fontSize":20,"bold":true},"compId":3},{"type":"Label","props":{"y":53,"x":20,"width":150,"text":"企业账户：","fontSize":20,"bold":false,"align":"right"},"compId":4},{"type":"Label","props":{"y":53,"x":169,"text":"1325969696","fontSize":20,"bold":false},"compId":5},{"type":"Label","props":{"y":83,"x":20,"width":150,"text":"账户余额：","fontSize":20,"bold":false,"align":"right"},"compId":6},{"type":"Label","props":{"y":83,"x":169,"width":117,"text":"3258.6元","height":20,"fontSize":20,"color":"#e81d1a","bold":false},"compId":7},{"type":"Text","props":{"y":81,"x":297,"text":"充值","fontSize":20,"color":"#0d2897","runtime":"laya.display.Text"},"compId":8},{"type":"Label","props":{"y":114,"x":20,"width":150,"text":"我的服务店：","fontSize":20,"bold":false,"align":"right"},"compId":9},{"type":"Label","props":{"y":114,"x":169,"text":"1325969696","fontSize":20,"bold":false},"compId":10}],"loadList":[],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}