/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.MyOrderControl;

	public class MyOrdersPanelUI extends Scene {
		public var orderbox:VBox;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/MyOrdersPanel");

		}

	}
}