/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.order.SelectFactoryControl;

	public class OderDetailPanelUI extends View {
		public var closebtn:Panel;
		public var orderoanel:Panel;
		public var orderbox:VBox;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/OderDetailPanel");

		}

	}
}