/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.OrderDetailControl;

	public class OrderDetailPanelUI extends View {
		public var mainpanel:Panel;
		public var orderoanel:Panel;
		public var orderbox:VBox;
		public var closebtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/OrderDetailPanel");

		}

	}
}