/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.OrganizeMrgControl;

	public class OrganizeMgrPanelUI extends View {
		public var memberlist:List;
		public var createOrganize:Button;
		public var organizelist:List;
		public var distributePanel:Box;
		public var organizeCom:ComboBox;
		public var moveOkbtn:Button;
		public var closeDist:Button;
		public var createOrganizePanel:Box;
		public var organizeNameInput:TextInput;
		public var createBtnOk:Button;
		public var btncloseCreate:Button;
		public var setAuthorityPanel:Box;
		public var confirmauthoritybtn:Button;
		public var closeauthoritybtn:Button;
		public var authorityRdo1:RadioGroup;
		public var authorityRdo2:RadioGroup;
		public var authorityRdo3:RadioGroup;
		public var authorityRdo4:RadioGroup;
		public var authorityRdo5:RadioGroup;
		public var accoutname:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/OrganizeMgrPanel");

		}

	}
}