/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.TransactionControl;

	public class TransactionPanelUI extends View {
		public var ordertime:Label;
		public var btnsearch:Button;
		public var transactionlist:List;
		public var itemNum:Label;
		public var pagetxt:Label;
		public var prebtn:Button;
		public var nextbtn:Button;
		public var moneytxt:Label;
		public var payamount:Label;
		public var reatryamount:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/TransactionPanel");

		}

	}
}