/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.TransactionControl;

	public class TransactionPanelUI extends View {
		public var transactionlist:List;
		public var pagetxt:Label;
		public var prebtn:Button;
		public var nextbtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/TransactionPanel");

		}

	}
}