/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import utils.AddMsgControl;

	public class AddCommentPanelUI extends View {
		public var inputmsg:TextInput;
		public var btnok:Button;
		public var btncancel:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/AddCommentPanel");

		}

	}
}