/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.AvgCutPanelControl;

	public class AverageCutPanelUI extends View {
		public var mainpanel:Panel;
		public var productlist:List;
		public var okbtn:Sprite;
		public var btnok:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/AverageCutPanel");

		}

	}
}