/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.ChooseDeliveryTimeControl;

	public class ChooseDeliveryTimePanelUI extends View {
		public var paybtn:Button;
		public var savebtn:Button;
		public var rawprice:Label;
		public var disountprice:Label;
		public var orderlist:List;
		public var closebtn:Button;
		public var timepreferRdo:RadioGroup;
		public var confirmpreferbtn:Button;
		public var setdefaultbtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/ChooseDeliveryTimePanel");

		}

	}
}