/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.ChooseDeliveryTimeControl;

	public class ChooseDeliveryTimePanelUI extends View {
		public var paybtn:Button;
		public var cancelbtn:Button;
		public var orderlist:List;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/ChooseDeliveryTimePanel");

		}

	}
}