/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.SelectTechControl;

	public class SelectTechPanelUI extends View {
		public var techcontent:Panel;
		public var btnok:Button;
		public var btncancel:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/SelectTechPanel");

		}

	}
}