/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.SelectMaterialControl;

	public class SelectAttachPanelUI extends View {
		public var attchesList:List;
		public var okbtn:Button;
		public var cancelbtn:Button;
		public var attachCatList:List;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/SelectAttachPanel");

		}

	}
}