/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import laya.html.dom.HTMLDivElement;
	import script.order.SelectPicControl;

	public class SelectPicPanelUI extends View {
		public var folderList:List;
		public var flder0:Label;
		public var flder1:Label;
		public var flder2:Label;
		public var htmltext:HTMLDivElement;
		public var radiosel:CheckBox;
		public var btnok:Button;
		public var picList:List;
		public var btncancel:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/SelectPicPanel");

		}

	}
}