/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.SelectAttchesControl;

	public class SelectAttchPanelUI extends View {
		public var attachList:List;
		public var btnok:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/SelectAttchPanel");

		}

	}
}