/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.SelectAddressControl;

	public class SelectAddressPanelUI extends View {
		public var btnadd:Button;
		public var inputsearch:TextInput;
		public var btnsearch:Button;
		public var list_address:List;
		public var btnok:Button;
		public var btncancel:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/SelectAddressPanel");

		}

	}
}