/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.SelectMaterialControl;

	public class SelectMaterialPanelUI extends View {
		public var main_panel:Panel;
		public var dragImg:Image;
		public var backBtn:Button;
		public var box_mat:Sprite;
		public var matlist:List;
		public var tablist:List;
		public var hasSelMat:Label;
		public var box_tech:Sprite;
		public var techcontent:Panel;
		public var mattext:Label;
		public var selecttech:Label;
		public var originimg:Image;
		public var yixingimg:Image;
		public var backimg:Image;
		public var yingxBack:Image;
		public var btnok:Button;
		public var btncancel:Button;
		public var numinput:TextInput;
		public var addbtn:Button;
		public var subtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/SelectMaterialPanel");

		}

	}
}