/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.SelectMaterialControl;

	public class SelectMaterialPanelUI extends View {
		public var main_panel:Panel;
		public var backBtn:Button;
		public var btnok:Button;
		public var btncancel:Button;
		public var box_mat:Sprite;
		public var matlist:List;
		public var tablist:List;
		public var box_tech:Sprite;
		public var techcontent:Panel;
		public var selecttech:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/SelectMaterialPanel");

		}

	}
}