/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;

	public class TabChooseBtnUI extends View {
		public var selbtn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{},"compId":2,"child":[{"type":"Button","props":{"y":0,"x":0,"var":"selbtn","stateNum":2,"skin":"button/clubDayoption.png","labelSize":26,"labelColors":"#FFFFFF,#CDCDCD","label":"条幅旗帜"},"compId":3}],"loadList":["button/clubDayoption.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}